### ISSUE TITLE
[Suggestion]: Change the Elven Kriegsmesser balance from Heavy to Swift

### ISSUE THREAD

**Issue by sanshoom** [Darkrp-community/OpenKeep#793]
### Category

Balance

### What is the suggestion?

I don't personally see how it makes sense that a class, which can roll only 12 strength at maximum (which is still unlikely to occur due to the -1 in str from being an elf) has a weapon with Heavy balance? So why not give it Swift balance instead? (side note: the supposedly 'lightweight' elven weapon has a 10 str requirement??)

### Why is this suggestion good?

Wouldn't Swift make more sense, given the fact that you can more often than not roll 13+ speed on Bladesinger, and the fact that it's an elven weapon that is supposedly 'lightweight' as referred to by the description of the weapon? It would compliment the class more.

![Screenshot 2024-09-25 130318](https://github.com/user-attachments/assets/5b290ec8-7893-443e-bbdd-8d2617822d3b)

**Comment by ThePainkiller** [comment]
It's a steel greatsword
It has steel greatsword attack datums and force
It is SUPPOSED to be a heavy weapon to swing, on a race that gets a -1 STR penalty this might sound ridiculous, hence the reduced minstr to wield it (from 12 to 10)
Swift is reserved for daggers and short weapons, not massive weapons with massive attack range. Giving Swift balance to a **greatsword** wielded exclusively by a race that gets SPD bonuses is a big no, for balance reasons.

At most, I could make it normal balance, so that it neither gains from STR nor from SPD, would that be good to symbolize the lightness of the blade?
