### ISSUE TITLE
[Suggestion]: the weight of chainmaille

### ISSUE THREAD

**Issue by FooliusIV** [Darkrp-community/OpenKeep#986]
### Category

Balance

### What is the suggestion?

Currently chainmail chest armor weight is balanced in an strange and gamey way. When the stats appear to be the same and the coverage is for the most part identical, with the addition of arm coverage for the steel haubergeon, and slightly buffed stats and leg coverage for the hauberk.

Iron chainmail is considered a light armor class item whereas its' steel equivalent (the haubergeon) and the hauberk are rendered medium armor class items. This makes little sense when iron is heavier than steel and otherwise the items (in case of the haubergeon) are pretty much identical - why would a vest of iron be so significantly lighter than a short sleeved shirt of steel?

Make the haubergeon light AC to eliminate the discrepancy I guess while acknowledging that a hauberk has more material and coverage and as a result might be significantly heavier.

### Why is this suggestion good?

It's good because it brings awareness to something that by the sounds of it has been overlooked.

**Comment by ThePainkiller** [comment]
If I had to code in code commentary for every single balance change I had to make, the code would be 90% code commentary 10% armor values

I will repeat it for the upteenth time, lest I have to leave a code comment to justify the changes

Iron chainmail becoming light armor was a COMPROMISE for armor values for light armor being on the range of a maximum of 60 melee for like, studded leather, and having SHIT armor values compared to medium, and the fact very few classes have medium armor training, and even fewer plate armor training.

**It was a compromise for the sake of light armor users, or NON-MEDIUM-ARMOR-PERK HAVERS, to get an at least somewhat decent armor for themselves without being toppled over**

No way in hell I'd approve any steel quality item, no matter how shit it is, to become a light armor, and it literally contradicts with the whole "armor feels gamey rn" comment considering hauberk literally covers the whole body and you can go barefoot and gloveless and use it as your one and only armor, for light users or dodge experts havers, with their armor values? Just in case the rethorical question wasn't clear enough, THAT would be unbalanced as fuck and gamey

The only other logical option would be to revert iron chainmail being light back to medium armor, but I know a lot of people who want to be a combat peasant during events and want not to be fucking toppled over would not like that either.

**Comment by FooliusIV** [comment]
It feels as though what I was trying to suggest was not communicated clearly

The hauberk should remain as it is, I do not want the hauberk made lighter. If any change should be made to it its' durability should be improved so that the armor trained have a truly more robust chain shirt.

The suggestion was that the haubergeon, the short sleeved light chain shirt which is through descriptions of iron and steel described as being lighter than its iron counterpart while miraculously being substantially heavier be made consistent with it's iron counterpart armor piece as they are otherwise practically the same thing sans short sleeves.  

I do not understand it being steel quality to have any impact on its weight or it's benefit over the iron vest to someone in a fight. I only sought to point out something that genuinely appeared inconsistent to me, and I do not anticipate that the server will keep dodge users as they are now.

I do not expect your answer to change, but I felt I needed to explain myself better.

**Comment by ThePainkiller** [comment]
> It feels as though what I was trying to suggest was not communicated clearly
> 
> The hauberk should remain as it is, I do not want the hauberk made lighter. If any change should be made to it its' durability should be improved so that the armor trained have a truly more robust chain shirt.
> 
> The suggestion was that the haubergeon, the short sleeved light chain shirt which is through descriptions of iron and steel described as being lighter than its iron counterpart while miraculously being substantially heavier be made consistent with it's iron counterpart armor piece as they are otherwise practically the same thing sans short sleeves.
> 
> I do not understand it being steel quality to have any impact on its weight or it's benefit over the iron vest to someone in a fight. I only sought to point out something that genuinely appeared inconsistent to me, and I do not anticipate that the server will keep dodge users as they are now.
> 
> I do not expect your answer to change, but I felt I needed to explain myself better.

This is one of the fringe cases in which I had to compromise realism over gameplay balance

I do know that wrought iron chainmaille would be realistically heavier than steel, however like I explained before, this was done to up the ceiling of Light Armor, because it had, like I said before, dogshit armor values on all its armors (gambeson, leather, studded leather, et al) and now they could have access to the most protective piece of all light armors: A humble iron chainmail (iron tier equipment)

After looking at integrity values through the new armor design introduced by Pig, I now realize the oversight you meant: The haubergeon and hauberk have standard durability (200), where they should have maximum (500) durability (steel tier equipment)

This will be fixed soon enough, I'll get to properly standardize armor durability on the tiers that it should (300 for iron, 500 for steel, 200 for every item on existance is already the norm, and 150 for things like clothing etc)

Haubergeon and Hauberk will **not** be considered light armor for the sake of balance. People are already complaining chain armor to be literally good at everything regardless, so we might have to touch down armor values a little, in general.

Iron chainmail, once more, is on the Light weight category out of a **concession** for non-medium-armor trained people

If the _consistency_ of weight classes is what you're worried about, like I said, I'll just make iron chainmail medium armor again and that way it will be "consistent" with the rest of chain-related armor pieces.

Fortunately some speed adjustments made dodge classes less of an overpowered issue now, and that's the whole reason I wanted to keep iron chainmail being light armor, to better protect their vitals with.

**Comment by FooliusIV** [comment]
I am honestly not certain about it, it was just something that I couldn't wrap my head around on my own and I wanted to I guess have the dialogue and understand the reasoning behind the decision in full. Suffice it to say at this point I do understand why it is classed as medium and I don't want you to feel compelled to make any change due to my own misgivings. 

It was a good concession, I just didn't understand what seemed to be a strange dichotomy when it came to metal shirts.
